### PR TITLE
Mozzi 2.0 master PR

### PR DESCRIPTION
**Pull request by tfry-git**
Not all pieces are in, yet, but we're getting there. Here's a "master" PR for monitoring the whole change set.

(We can still create and merge "sub"-PRs into the devel/Mozzi2 branch, and they should end up, here).

Notes:
- The flash increases on some boards appear to be solely due to the fact that HIFI/STEREO sketches are now actually using HIFI/STEREO

### CODE REVIEW

**Comment by tfry-git** [comment]
There are a couple of items left at #210 , but those can really be handled, incrementally, as far as I can see. Also, I'm a little afraid, waiting for every box to be truly ticked will cause out-of-proportion delays. So what I'd like to propose is to finally go ahead and make the switch to Mozzi 2.0. (It's a small step in git, but...)

My checklist of stuff that *really* still needs to be done (please add your items, if any):
  - [ ] updating the doxygen documentation (my last attempt was not so very successful. @tomcombriat , have you done that, before?)
  - [ ] we probably want to preserve the current master as a "Mozzi1" branch, just in case
  - [ ] the documentation changes (#229) will have to be merged in sync with this
  - [ ] the usual release steps

**Comment by sensorium** [comment]
I tested generating the docs on my setup, loading extras/doxygen-style/Doxyfile into Doxygen, and it still seems to work OK.  You might have to adjust some of the local directory entries, though the only obvious one I see is in "Step 1" on the Doxygen gui, which is the working directory.

**Comment by tomcombriat** [comment]
>  (my last attempt was not so very successful. @tomcombriat , have you done that, before?)

Not for Mozzi and I have to say that I am not very experienced with Doxygen, but I can try to help on what @sensorium has done (if changes are needed).

> we probably want to preserve the current master as a "Mozzi1" branch, just in case

Yes, I also wanted to suggest that. This can be especially useful for git users wanted to recompile old sketches done with Mozzi1 (like me for instance): people using the Arduino Library Manager can do that easily, but I never found a way to switch from a tag to another. Switching to another branch is super straightforward (but might be worth documenting).

**Comment by sensorium** [comment]
On looking at the generated docs, I didn't find the classes (Oscil, filters etc.).  Not sure if it's due to something that's changed in the source files, or in the Doxygen software/config.  It's been a while and I'd almost need to start understanding it all over again step by step to work it out... (sorry to be not much help).

**Comment by tfry-git** [comment]
Ok, I think the API docs and web page *may* be ready, now. (In doxygen I still had to add some ```@defgroup``` statements. For the web page, I also synced examples, and API, now.

Could you take another close look at docs and page? (https://tfry-git.github.io/Mozzi/)

**Comment by tomcombriat** [comment]
Hi,
A lot of work has been done! Sorry for being a bit away lately.

I am checking the new things now. I do not have a clear overview of the website yet (for instance I still do not get how to generate the doc from one branch and transfer it to the other…) so I will update a list here and try to implement the changes myself. Everything unticked is what I did not implement, yet.

 - [ ] Dependencies: I would add `FixMath` as a non-included dependency on the main page
 - [ ] https://tfry-git.github.io/Mozzi/learn/output/#output-using-a-true-hardware-dac : "Teensy 3.1, Arduino Giga, and ESP32. Note however, that for the latter two, the output resolution is only 8 bits." the ADC resolution of the Giga is actually 12bits if I am correct.

**Comment by sensorium** [comment]
The learn/a-simple-sketch/ section (points to the online version at the moment) could do with updating to reflect changes...
- updateAudio() in the sketch parts
- references to STANDARD audio mode maybe not relevant now
- include different headers? (I'm not on top of the new version yet!)
- comments at the end about floating point , fixed math and speed might be out of date

**Comment by sensorium** [comment]
By the way, feel free to change whatever you like in the web pages, I recognise how much work has been done and I don't feel the need to keep anything there in its old condition...

**Comment by tomcombriat** [comment]
@sensorium Are we on the same version? The sketch in the [page you referred](https://tfry-git.github.io/Mozzi/learn/a-simple-sketch/) seems fairly up-to-date to me (except for FixMath actually, and a bit of syntaxic color).

**Comment by sensorium** [comment]
@tomcombriat, yes I must have been viewing the wrong version!

**Comment by tomcombriat** [comment]
Except some minor details (see previous comment), I think it looks good! I actually kinda like the black theme also ;). Some things could be made even more perfect but I think it is also nice to put it out as minor changes will inevitably occur but it is in a good working and documentation state.
 I think that we will have to be quite careful in the changelog, the automatic one won't be of much help. Things that need to be in there (probably incomplete list, add items if you see something that got forgotten):
 - suppression of `mozzi_config.h`: config is done at the beginning of the sketches
 - license changed
 - new FixMath
 - this might not conserve compatibility and point to the previous branch/version

**Comment by tfry-git** [comment]
- Regarding the Changelog: There's also extras/NEWS.txt, I made some updates, there.
- Fixed some refs in the doxygen, as pointed out, but these still need to be synced to the pages. (In the long run, the whole doxygen thing should be automated in a github action, but that's certainly for another day).
- Regarding the table of supported boards: Yes, that's duplicated in the docs, and probably unnecessarily so. However that's done by including the same table twice, so no danger, within the pages. What worries me more is the duplication between README.md (including that same table) and the pages. I tried to get the two most back in sync, but that really is an all manual process.

**Comment by tomcombriat** [comment]
Maybe a stupid question, but why do we have separate cases for in-built DAC and PWM? Usually, one excludes the other  and the result is the same: sound straight from the board, maybe, at some point, we could consider merging them in `MOZZI_OUTPUT_PWM_DAC`? This might lead to a slight confusion to know if it is a real DAC or PWM but…

**Comment by tfry-git** [comment]
If DAC and PWM are mutually exclusive, today, I think that's mostly because we were too lazy to implement a PWM mode for boards that come with a DAC. Yet, having an inbuilt non-DAC mode will sometimes still make a lot of sense, e.g. because the DAC is limited to mono (Teensy 3, SAMD, Uno R4) or 8 bits (ESP32), or tied to specific pins that might be needed for something else.

We do already have a PDM mode in addition to DAC on ESP32, and I don't see anything _logically_ going against both PWM and DAC supported in the same port. Besides, users who simply want "either DAC or PWM on any pin" will generally be good with the default output mode, anyway.

**Comment by tomcombriat** [comment]
Very good points!

**Comment by tfry-git** [comment]
Are we good to go?

When would be a good time? (Probably an official release / announcement should follow shortly after merging)

**Comment by sensorium** [comment]
I'm happy if you're ready to go ahead...

**Comment by sensorium** [comment]
...(whenever you like)

**Comment by tomcombriat** [comment]
> Are we good to go?

I think so! If some details went under the radar we can always fix them as we go.

I think we should make a nice, and clear announcement, emphasing on possible loss of compatibility and the new features. I can try to draft a release that everyone can edit soon if you want!

**Comment by tomcombriat** [comment]
(Release draft started at: https://github.com/sensorium/Mozzi/releases)

**Comment by tomcombriat** [comment]
> (Release draft started at: https://github.com/sensorium/Mozzi/releases)

Drafty for now, I am writing it as it comes. Please feel free to add/modify/delete. The changelog will come when merged (but might be un-readable).

I changed the genus of mosquitoes as this is a major version, but we can come back to Aedes if you prefer!

**Comment by tomcombriat** [comment]
Hello!
Any opinion on the release draft?

**Comment by tfry-git** [comment]
Oh, yes, I've been distracted. I had done some small edits to the draft, and am totally fine with it.

Shall I just go ahead and do the merges (this PR, and the website)?

**Comment by tomcombriat** [comment]
> Shall I just go ahead and do the merges (this PR, and the website)?

Yup, I think so :). The changelog can be added to the draft once it is merged.

I'll post the same on the forum once it is done!

**Pull request merged**
