### PR TITLE
Fix/tables

### LINKED ISSUE #279: 8-bit Sine tables to not describe sines, but rather negative cosines
Most of the sine tables do not start at the origin, but rather at -128.  This is bad because it can cause a click if the wave is played raw.  They should start at 0, then increase from there, then back down to -128.

### PR DESCRIPTION
**Pull request by tomcombriat**
Fix #279

### CODE REVIEW

**Comment by tomcombriat** [comment]
Alright, this also fixes #280. Here was my method:

 - for "mathematical" tables, like saw, tri, cos and sin, I recomputed them from scratch, for instance:

``` python
length = 2048

dat = []
out = open("out.txt","w")
t = np.linspace(0,2*np.pi,num=length,endpoint=False)
out.write("\t")
for i in range(len(t)):
    #out.write(str(round(127*np.sin(t[i])))+", ") # for the sin
    #out.write(str(round(-127+127*2.*i/(length-1)))+", ")  # for the saw
    # for the tri
    if (i<=length/4):
        dat.append(i*127./length*4)
    elif (i<=length*3/4):
        dat.append(127-(i-length/4)*(127*2)/(length/2))
    else:
        dat.append(-127.+127.*(i-length*3/4)/length*4)
```
for the `sin`.

 - tables that were not touching `-128` were left as they were.
 - other special tables (noises, scaler, waveshaper and actually square), I tried to touch them as little as possible, just rescaling slightly to get rid of the -128:

```python
if (np.amin(data)==-128):
    data = (data-np.amin(data)) * (np.amax(data)-(np.amin(data)+1)) / (np.amax(data) - np.amin(data)) + np.amin(data)+1
```
where `data` is the original content of the table. This rescale between the original maximum and -127 if the original table was going to -128.
 Note that this does not ensure that tables have a 0-mean, but that was not necessary the case to begin with. I think it is better to keep the tables as close as possible for their original which this is achieving.

What do you think?

**Comment by tomcombriat** [comment]
For reproducibility purposes, I added the script I used to regenerate the "standard" tables. Plus the tables automatically generated.

**Comment by tomcombriat** [comment]
Any opinion? Can I merge this?

**Comment by sensorium** [comment]
Great work Tom.  OK by me to merge.

**Pull request merged**
