### PR TITLE
Added new examples to gh-pages

### PR DESCRIPTION
**Pull request by tomcombriat**

### CODE REVIEW

**Comment by tomcombriat** [comment]
Sorry, I had a problem in my git config, so I think I messed a few things in the `devel/gh-pages2` branch (which I guess is not used anyway, should we delete it?).

Here is a PR for updating the website: added the new examples, with audio and also some of my work as discussed rapidly by mail. It is the first time I work on the website so a second look is welcome!

**Comment by tomcombriat** [comment]
And, the audio I generated do not play, will try to fix tomorrow…

**Comment by tfry-git** [comment]
> ~Sorry, I had a problem in my git config, so I think I messed a few things in the `devel/gh-pages2` branch (which I guess is not used anyway, should we delete it?).~ (Undone)

Yes, I guess we can delete this (although you seem to have changed your mind on that?). I had created that for staging the changes for Mozzi2.

> Here is a PR for updating the website: added the new examples, with audio and also some of my work as discussed rapidly by mail. It is the first time I work on the website so a second look is welcome!

Looks good to me. But yes, the annoying thing is that it isn't easily possible to preview the changes in a live website (you may recall, I set up a test-site from a personal fork for Mozzi2, but that was pretty cumbersome, as well).

**Comment by tomcombriat** [comment]
> Looks good to me. But yes, the annoying thing is that it isn't easily possible to preview the changes in a live website (you may recall, I set up a test-site from a personal fork for Mozzi2, but that was pretty cumbersome, as well).

Well, actually, you can look at: https://tomcombriat.github.io/Mozzi/, except as some of the audio files do not play because the url is pointing to sensorium's repo. The gh-action for web deployment on my own repo actually helped me to find some of the errors. It deployed okay with the last commits so I think there are no big mistakes.

**Comment by tomcombriat** [comment]
> Yes, I guess we can delete this (although you seem to have changed your mind on that?). 

No, I just reverted the changes I made there in order not to create some confusion. I am in favor of deleting it.

**Pull request merged**
