### PR TITLE
Fixed compilation for Teensy2

### PR DESCRIPTION
**Pull request by tomcombriat**
Looks like a typo, but do not have the hardware to try…

### CODE REVIEW

**Comment by tfry-git** [comment]
Yes, clearly a typo. But no, I don't have a Teensy board, either.

@sensorium Could you enable the permission  "Send write tokens to workflows from fork pull requests" as per https://github.com/arduino/report-size-deltas?tab=readme-ov-file#run-from-a-scheduled-workflow ?

**Comment by tfry-git** [comment]
And here's the offending commit introducing the error: https://github.com/sensorium/Mozzi/commit/51ae09a918a81009a38d47996a79cc179dc77bd3

**Comment by tomcombriat** [comment]
Alright. If you agree I'm in favour of merging, and worse case changing it again if it does not work as intended: that only affects Teensy2 and at least it compiles now…

**Comment by sensorium** [comment]
> permission "Send write tokens to workflows from fork pull requests" as per https://github.com/arduino/report-size-deltas?tab=readme-ov-file#run-from-a-scheduled-workflow ?

Hi @tfry-git , I followed the link from that page to "Send write tokens to workflows from fork pull requests", and that option seems to be only available for private repos?  I couldn't find that permission in my settings under actions/general... should I look somewhere else?

**Comment by tfry-git** [comment]
> > permission "Send write tokens to workflows from fork pull requests" as per https://github.com/arduino/report-size-deltas?tab=readme-ov-file#run-from-a-scheduled-workflow ?
> 
> Hi @tfry-git , I followed the link from that page to "Send write tokens to workflows from fork pull requests", and that option seems to be only available for private repos? I couldn't find that permission in my settings under actions/general... should I look somewhere else?

Hm, I can't seem to find the option, either. Sorry for sending you to a dead end.

**Pull request merged**
